"""
Data cleaning and integration.

Every transformation appends a human-readable line to a `CleaningLog`, which
is written to reports/cleaning_log.md. That log is a project deliverable --
"clear documentation of preprocessing steps" is an explicit grading criterion,
so the audit trail is generated by the code rather than written by hand.

Cleaning order matters and is deliberate:
  1. normalise column names / dtypes      (so later steps can rely on them)
  2. standardise categorical text         (before dedup -- ' Family ' and
                                           'FAMILY' must collapse first)
  3. drop exact duplicates
  4. repair invalid values (ratings, months)
  5. enforce referential integrity
  6. impute what remains
  7. join into one master table
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from .config import CLEANING_LOG, RATING_MAX, RATING_MIN, RAW_TABLES


@dataclass
class CleaningLog:
    """Accumulates an ordered, auditable record of every cleaning action."""

    entries: list[tuple[str, str, int]] = field(default_factory=list)

    def add(self, step: str, detail: str, affected: int = 0) -> None:
        self.entries.append((step, detail, affected))

    def to_markdown(self) -> str:
        lines = [
            "# Data Cleaning Log",
            "",
            "Generated automatically by `src/cleaning.py`. Each row records one",
            "transformation applied to the raw data and how many rows or cells it touched.",
            "",
            "| # | Step | Detail | Rows/cells affected |",
            "|---|------|--------|--------------------|",
        ]
        for i, (step, detail, n) in enumerate(self.entries, 1):
            lines.append(f"| {i} | {step} | {detail} | {n:,} |")
        return "\n".join(lines) + "\n"

    def save(self, path=CLEANING_LOG) -> None:
        path.write_text(self.to_markdown(), encoding="utf-8")

    def __len__(self) -> int:
        return len(self.entries)


# --------------------------------------------------------------------------
# Primitive helpers
# --------------------------------------------------------------------------
def _clean_text(s: pd.Series) -> pd.Series:
    """Trim, collapse internal whitespace, and apply consistent Title Case."""
    out = s.astype("string").str.strip().str.replace(r"\s+", " ", regex=True)
    # Title-case only if the value isn't a deliberate acronym (e.g. "UAE").
    def fix(v):
        if pd.isna(v):
            return v
        return v if (v.isupper() and len(v) <= 4) else v.title()
    return out.map(fix)


def _to_int(s: pd.Series) -> pd.Series:
    """Coerce to nullable integer, tolerating '12.0' and stray whitespace."""
    return pd.to_numeric(s, errors="coerce").astype("Float64").round().astype("Int64")


# Canonical column vocabulary, derived from the schema in config. Any incoming
# column whose letters/digits match one of these (ignoring case, spaces and
# underscores) is renamed to the canonical spelling.
_CANONICAL_COLUMNS = {
    re.sub(r"[^a-z0-9]", "", c.lower()): c
    for spec in RAW_TABLES.values()
    for c in spec["columns"]
}


def _snake_to_pascal(col: str) -> str:
    """
    Normalise a column name to its canonical PascalCase spelling.

    Matching is done on letters and digits only, so `visit_month`, `Visit Month`
    and `VISITMONTH` all resolve to `VisitMonth`. Names already in canonical
    form pass through untouched -- calling `.title()` on them would corrupt the
    internal capitals ('TransactionId' -> 'Transactionid').
    """
    name = str(col).strip()
    key = re.sub(r"[^a-z0-9]", "", name.lower())
    if key in _CANONICAL_COLUMNS:
        return _CANONICAL_COLUMNS[key]
    # Unknown column: fall back to a sensible PascalCase rendering.
    if re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name) and not name.islower() and not name.isupper():
        return name
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", name) if p]
    return "".join(p.capitalize() for p in parts) or name


# --------------------------------------------------------------------------
# Per-table cleaning
# --------------------------------------------------------------------------
def clean_lookup_tables(tables: dict[str, pd.DataFrame], log: CleaningLog) -> dict[str, pd.DataFrame]:
    """Normalise the eight dimension tables: ids to Int64, labels to clean text."""
    out = {}
    text_cols = {
        "city": "CityName", "attraction_type": "AttractionType",
        "visit_mode": "VisitMode", "continent": "Continent",
        "country": "Country", "region": "Region",
    }

    for name, df in tables.items():
        if name == "transaction":
            out[name] = df.copy()
            continue

        df = df.copy()
        df.columns = [_snake_to_pascal(c) for c in df.columns]

        for c in df.columns:
            if c.endswith("Id"):
                df[c] = _to_int(df[c])

        if name in text_cols and text_cols[name] in df.columns:
            col = text_cols[name]
            before = df[col].astype("string")
            df[col] = _clean_text(df[col])
            changed = int((before.fillna("\x00") != df[col].fillna("\x00")).sum())
            if changed:
                log.add(
                    "Standardise text",
                    f"`{name}.{col}` — trimmed whitespace and unified casing",
                    changed,
                )

        if name == "item":
            for c in ("Attraction", "AttractionAddress"):
                if c in df.columns:
                    df[c] = df[c].astype("string").str.strip().str.replace(r"\s+", " ", regex=True)

        # Dimension tables must have unique primary keys.
        key = f"{name.title().replace('_', '')}Id"
        pk_candidates = [c for c in df.columns if c.endswith("Id")]
        if pk_candidates:
            pk = pk_candidates[0]
            dupes = int(df.duplicated(subset=[pk]).sum())
            if dupes:
                df = df.drop_duplicates(subset=[pk], keep="first")
                log.add("Deduplicate", f"`{name}` — removed rows with repeated `{pk}`", dupes)

        out[name] = df

    return out


def clean_transactions(df: pd.DataFrame, tables: dict[str, pd.DataFrame], log: CleaningLog) -> pd.DataFrame:
    """Clean the fact table: the only table where row-level defects matter."""
    df = df.copy()
    df.columns = [_snake_to_pascal(c) for c in df.columns]
    start_rows = len(df)

    # --- dtypes -----------------------------------------------------------
    for c in ("TransactionId", "UserId", "AttractionId", "VisitYear", "VisitMonth"):
        if c in df.columns:
            df[c] = _to_int(df[c])
    df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

    # --- categorical standardisation (before dedup) -----------------------
    if "VisitMode" in df.columns:
        if pd.api.types.is_numeric_dtype(df["VisitMode"]):
            # Some copies of the dataset store VisitMode as an id.
            vm = tables["visit_mode"]
            mapping = dict(zip(_to_int(vm["VisitModeId"]), _clean_text(vm["VisitMode"])))
            df["VisitMode"] = _to_int(df["VisitMode"]).map(mapping)
            log.add("Decode ids", "`transaction.VisitMode` — mapped ids to labels via Mode table", len(df))
        else:
            before = df["VisitMode"].astype("string")
            df["VisitMode"] = _clean_text(df["VisitMode"])
            changed = int((before.fillna("\x00") != df["VisitMode"].fillna("\x00")).sum())
            if changed:
                log.add(
                    "Standardise text",
                    "`transaction.VisitMode` — trimmed whitespace and unified casing "
                    "(e.g. `' FAMILY '` → `'Family'`)",
                    changed,
                )

        # Fold near-duplicate labels onto the canonical vocabulary.
        canonical = set(_clean_text(tables["visit_mode"]["VisitMode"]).dropna())
        synonyms = {"Solo Traveller": "Solo", "Solo Travel": "Solo", "Businesss": "Business"}
        unknown = set(df["VisitMode"].dropna().unique()) - canonical
        fixed = 0
        for u in unknown:
            target = synonyms.get(u)
            if target is None:
                # Case/space-insensitive fallback match.
                for c in canonical:
                    if _normalise_label(u) == _normalise_label(c):
                        target = c
                        break
            if target:
                n = int((df["VisitMode"] == u).sum())
                df.loc[df["VisitMode"] == u, "VisitMode"] = target
                fixed += n
        if fixed:
            log.add("Reconcile categories",
                    "`transaction.VisitMode` — folded variant spellings onto the Mode vocabulary",
                    fixed)

    # --- exact duplicates -------------------------------------------------
    dupe_mask = df.duplicated(keep="first")
    n_dupes = int(dupe_mask.sum())
    if n_dupes:
        df = df[~dupe_mask]
        log.add("Deduplicate", "`transaction` — dropped fully identical rows", n_dupes)

    dupe_id = int(df.duplicated(subset=["TransactionId"]).sum())
    if dupe_id:
        df = df.drop_duplicates(subset=["TransactionId"], keep="first")
        log.add("Deduplicate", "`transaction` — dropped repeated `TransactionId`", dupe_id)

    # --- invalid values ---------------------------------------------------
    bad_rating = df["Rating"].notna() & (
        (df["Rating"] < RATING_MIN) | (df["Rating"] > RATING_MAX)
    )
    n_bad = int(bad_rating.sum())
    if n_bad:
        df.loc[bad_rating, "Rating"] = np.nan
        log.add("Repair outliers",
                f"`transaction.Rating` — values outside [{RATING_MIN}, {RATING_MAX}] set to null",
                n_bad)

    bad_month = df["VisitMonth"].notna() & (~df["VisitMonth"].between(1, 12))
    n_bm = int(bad_month.sum())
    if n_bm:
        df.loc[bad_month, "VisitMonth"] = pd.NA
        log.add("Repair outliers", "`transaction.VisitMonth` — values outside 1–12 set to null", n_bm)

    if "VisitYear" in df.columns:
        bad_year = df["VisitYear"].notna() & (~df["VisitYear"].between(1990, 2035))
        n_by = int(bad_year.sum())
        if n_by:
            df.loc[bad_year, "VisitYear"] = pd.NA
            log.add("Repair outliers", "`transaction.VisitYear` — implausible years set to null", n_by)

    # --- referential integrity -------------------------------------------
    valid_users = set(tables["user"]["UserId"].dropna())
    valid_items = set(tables["item"]["AttractionId"].dropna())

    orphan = (~df["UserId"].isin(valid_users)) | (~df["AttractionId"].isin(valid_items))
    n_orphan = int(orphan.sum())
    if n_orphan:
        df = df[~orphan]
        log.add("Referential integrity",
                "`transaction` — removed rows whose `UserId`/`AttractionId` has no matching "
                "record in the User/Item tables",
                n_orphan)

    # --- imputation -------------------------------------------------------
    # Ratings are the regression target: rows without one cannot supervise the
    # model, so they are dropped rather than imputed (imputing the target would
    # teach the model the imputation rule, not user behaviour).
    n_null_rating = int(df["Rating"].isna().sum())
    if n_null_rating:
        df = df[df["Rating"].notna()]
        log.add("Handle missing",
                "`transaction.Rating` — dropped rows with no rating (target variable; "
                "imputing it would leak the imputation rule into the model)",
                n_null_rating)
    df["Rating"] = df["Rating"].astype(int)

    # VisitMode is the classification target; same reasoning.
    if "VisitMode" in df.columns:
        n_null_mode = int(df["VisitMode"].isna().sum())
        if n_null_mode:
            df = df[df["VisitMode"].notna()]
            log.add("Handle missing",
                    "`transaction.VisitMode` — dropped rows with no visit mode (target variable)",
                    n_null_mode)

    # Month/year are features: impute with the mode, which preserves seasonality
    # better than a constant and keeps the row usable.
    for c in ("VisitMonth", "VisitYear"):
        if c in df.columns and df[c].isna().any():
            n = int(df[c].isna().sum())
            fill = int(df[c].mode(dropna=True).iloc[0])
            df[c] = df[c].fillna(fill).astype(int)
            log.add("Handle missing", f"`transaction.{c}` — imputed with modal value `{fill}`", n)
        elif c in df.columns:
            df[c] = df[c].astype(int)

    log.add("Summary",
            f"`transaction` — {start_rows:,} raw rows → {len(df):,} clean rows "
            f"({start_rows - len(df):,} removed, {(start_rows - len(df)) / start_rows:.2%})",
            len(df))
    return df


def _normalise_label(v: str) -> str:
    return re.sub(r"[^a-z0-9]", "", str(v).lower())


# --------------------------------------------------------------------------
# Integration
# --------------------------------------------------------------------------
def build_master_dataset(tables: dict[str, pd.DataFrame], log: CleaningLog) -> pd.DataFrame:
    """
    Join the fact table to every dimension, producing one analysis-ready row
    per transaction with human-readable geography and attraction labels.

    All joins are LEFT from the transaction table so the fact grain is never
    silently changed; row count is asserted afterwards.
    """
    txn = tables["transaction"]
    n_before = len(txn)

    user = tables["user"].rename(columns={"CityId": "UserCityId"})
    df = txn.merge(user, on="UserId", how="left", validate="many_to_one")

    city = tables["city"][["CityId", "CityName", "CountryId"]]
    df = df.merge(
        city.rename(columns={"CityId": "UserCityId", "CountryId": "CityCountryId"}),
        on="UserCityId", how="left", validate="many_to_one",
    )

    df = df.merge(tables["continent"], on="ContinentId", how="left", validate="many_to_one")
    df = df.merge(
        tables["region"][["RegionId", "Region"]], on="RegionId", how="left", validate="many_to_one"
    )
    df = df.merge(
        tables["country"][["CountryId", "Country"]], on="CountryId", how="left", validate="many_to_one"
    )

    item = tables["item"]
    df = df.merge(item, on="AttractionId", how="left", validate="many_to_one")
    df = df.merge(
        tables["attraction_type"], on="AttractionTypeId", how="left", validate="many_to_one"
    )
    df = df.merge(
        city.rename(columns={"CityId": "AttractionCityId", "CityName": "AttractionCity"})
            .drop(columns=["CountryId"]),
        on="AttractionCityId", how="left", validate="many_to_one",
    )

    assert len(df) == n_before, (
        f"Join changed the fact grain: {n_before:,} → {len(df):,} rows. "
        "A dimension table has duplicate keys."
    )

    log.add("Integrate",
            "Joined transaction → user → city/country/region/continent and "
            "→ item → attraction type/city (all LEFT joins, fact grain preserved)",
            len(df))

    # Residual nulls from left joins: label rather than drop, so a missing
    # city does not cost us an otherwise complete transaction.
    for c in ["Continent", "Region", "Country", "CityName", "AttractionType",
              "AttractionCity", "Attraction"]:
        if c in df.columns and df[c].isna().any():
            n = int(df[c].isna().sum())
            df[c] = df[c].astype("object").fillna("Unknown")
            log.add("Handle missing",
                    f"`{c}` — unmatched dimension lookups labelled `'Unknown'`", n)

    return df


def run_cleaning(tables: dict[str, pd.DataFrame]) -> tuple[pd.DataFrame, CleaningLog]:
    """Full cleaning entry point: returns the master dataset and the audit log."""
    log = CleaningLog()
    cleaned = clean_lookup_tables(tables, log)
    cleaned["transaction"] = clean_transactions(cleaned["transaction"], cleaned, log)
    master = build_master_dataset(cleaned, log)
    return master, log
